class Locale:
    def __init__(self, language):
        if language == "en":
            self.report = "Report"
            self.utils = "Utilities"
            self.register_new_user = "Register new user"
            self.own_keys_sb = "Secure Boot own keys enrolled"
            self.ms_keys = "Microsoft keys enrolled"
            self.vendor_keys = "Vendor keys enrolled"
            self.tpm_exists = "TPM exists"
            self.tpm_enrolled = "Device unlock with TPM"
            self.tpm_pin = "Unlock with TPM + PIN"
            self.drive = "Drive"
            self.enroll_tpm = "Enroll TPM"
            self.delete_tpm = "Delete TPM"
            self.enroll_recovery = "Enroll recovery key"
            self.delete_recovery = "Delete recovery keys"
            self.delete_password = "Delete passwords"
            self.enroll_password = "Enroll password"
            self.luks_password = "Encrypted partition password"
            self.use_pin = "Use PIN-code"
            self.pin_1 = "Enter PIN"
            self.pin_2 = "Enter PIN (repeat)"
            self.enroll = "Enroll"
            self.next = "Next"
            self.pin_mismatch = "PIN-codes mismatch!"
            self.pin_msg = "PIN-codes mismatch. Please try again!"
            self.exit = "Exit"
            self.short_pin = "Short PIN"
            self.short_pin_msg = "PIN must be at least 4 characters"
            self.enroll_tpm_error = "TPM enrollment error"
            self.enroll_tpm_error_msg = "An error occurred while enrolling the TPM. Please check that your password is correct."
            self.delete_tpm_success = "TPM drive unlocking successfully disabled."
            self.delete_tpm_failure = "An error occurred while deleting the TPM enrollment."
            self.enroll_recovery_failure = "An error occurred while enrolling the recovery key. Please check your password."
            self.delete_recovery_success = "Disk unlocking with recovery keys has been successfully disabled."
            self.delete_recovery_failed = "An error occurred while deleting recovery keys"
            self.remaining_password = "Enter recovery key"
            self.delete_password_success = "Disk unlocking with passwords has been successfully disabled."
            self.delete_password_failed = "An error occurred while deleting passwords"
            self.remaining_password_true = "Enter password or recovery key"
            self.enter_password_1 = "Enter new password"
            self.enter_password_2 = "Enter new password (repeat)"
            self.passwords_differ = "Passwords are different. Please try again."
            self.enroll_password_error = "An error occurred while enrolling your password. Please check your password."
            self.enroll_password_success = "Enrollment of new password was successful."
            self.copy = "Copy"
            self.error = "Error"
            self.luks_failed = "Failed to detect LUKS partition. Are you running manager from SECUX Linux?"
            self.update = "Update"
            self.update_msg = "Securitymanager updater"
            self.after_update = "To apply updates, you must restart the program"
            self.preset_secure = "Secure (own Secure Boot keys)"
            self.preset_lessecure = "Backwards compatible (having Microsoft keys)"
            self.preset_custom = "Custom"
            self.tpm_preset = "Disk Unlock Profile"
            self.sign_policy = "PCR Signing Policy"
            self.PCRs_info = ["UEFI executable code", "Host platform configuration", 
                              "UEFI OpROM", "OpROM hardware info",
                              "Boot loader binary and extensions", "GPT/Partition table", "OEM specific data",
                              "SecureBoot state (including keys)", "Kernel cmdline (GRUB)", "All files read (GRUB)", "IMA measurement log", 
                              "UKI components; boot process stages", "UKI cmdline",
                              "UKI initrd extensions", "MOK certificates and hashes", "Encryption key, UUIDs, mountpoints"]


        elif language == "ru":
            self.report = "Отчёт"
            self.utils = "Утилиты"
            self.register_new_user = "Регистрация пользователя"
            self.own_keys_sb = "Загружены собственные ключи Secure Boot"
            self.ms_keys = "Загружены ключи Microsoft"
            self.vendor_keys = "Загружены ключи производителя"
            self.tpm_exists = "Наличие TPM"
            self.tpm_enrolled = "Разблокировка диска с помощью TPM"
            self.tpm_pin = "Разблокировка с TPM + PIN"
            self.drive = "Диск"
            self.enroll_tpm = "Зарегистрировать TPM"
            self.delete_tpm = "Удалить TPM"
            self.enroll_recovery = "Зарегистрировать ключ восстановления"
            self.delete_recovery = "Удалить ключи восстановления"
            self.delete_password = "Удалить пароли"
            self.enroll_password = "Зарегистрировать пароль"
            self.luks_password = "Пароль от зашифрованного раздела"
            self.use_pin = "Использовать ПИН-код"
            self.pin_1 = "Введите ПИН"
            self.pin_2 = "Введите ПИН (повтор)"
            self.enroll = "Зарегистрировать"
            self.next = "Далее" 
            self.pin_mismatch = "ПИН-коды отличаются"
            self.pin_msg = "ПИН-коды отличаются. Пожалуйста, попробуйте снова!"
            self.exit = "Выйти"
            self.short_pin = "Короткий ПИН-код"
            self.short_pin_msg = "ПИН-код должен содержать как минимум 4 символа"
            self.enroll_tpm_error = "Ошибка регистрации TPM"
            self.enroll_tpm_error_msg = "Произошла ошибка при регистрации TPM. Проверьте правильность пароля."
            self.success = "Успех"
            self.enroll_tpm_success = "Регистрация разблокировки диска с помощью TPM произошла успешно."
            self.failure = "Ошибка"
            self.enroll_tpm_failure = "Произошла ошибка в время регистрации."
            self.delete_tpm_success = "Разблокировка диска с помощью TPM успешно отключена."
            self.delete_tpm_failure = "Произошла ошибка в время удаления регистрации TPM."
            self.enroll_recovery_failure = "Произошла ошибка в время регистрации ключа восстановления. Проверьте пароль."
            self.delete_recovery_success = "Разблокировка диска с помощью ключей восстановления успешно отключена."
            self.delete_recovery_failed = "Произошла ошибка в время удаления ключей восстановления"
            self.remaining_password = "Введите ключ восстановления"
            self.delete_password_success = "Разблокировка диска с помощью паролей успешно отключена."
            self.delete_password_failed = "Произошла ошибка в время удаления паролей"
            self.remaining_password_true = "Введите пароль или ключ восстановления"
            self.enter_password_1 = "Введите новый пароль"
            self.enter_password_2 = "Введите новый пароль (повтор)"
            self.passwords_differ = "Пароли отличаются. Пожалуйста, попробуйте снова."
            self.enroll_password_error = "Произошла ошибка в время регистрации пароля. Проверьте пароль."
            self.enroll_password_success = "Регистрация нового пароля произошла успешно."
            self.copy = "Скопировать"
            self.error = "Ошибка"
            self.luks_failed = "Не удалось определить зашифрованный раздел. Вы точно запускаете программу из под SECUX Linux?"
            self.update = "Обновить"
            self.update_msg = "Обновление securitymanager"
            self.after_update = "Для применения обновлений необходимо перезапустить программу"
            self.preset_secure = "Безопасный (собственные ключи Secure Boot)"
            self.preset_lesssecure = "Обратная совместимость (наличие ключей Microsoft)"
            self.preset_custom = "Собственный"
            self.tpm_preset = "Профиль разблокировки диска"
            self.sign_policy = "Политика подписи PCR"
            self.PCRs_info = ["Исполняемый код UEFI", "Конфигурация платформы хоста",
                            "UEFI OpROM", "Информация об оборудовании OpROM",
                            "Файл и расширения загрузчика", "Таблица GPT/разделов", "Данные OEM",
                            "Состояние SecureBoot (включая ключи)", "Командная строка ядра (GRUB)", "Все прочитанные файлы (GRUB)", "Журнал измерений IMA",
                            "Компоненты UKI; этапы процесса загрузки", "Командная строка UKI",
                            "Расширения UKI initrd", "Сертификаты и хэши MOK", "Ключ шифрования, UUID, точки монтирования"]
