#!/bin/bash

build() {
    add_runscript

    add_file "/etc/idp.json"
    
    add_binary /usr/bin/tpm2_pcrread
    add_binary /usr/bin/tpm2_startauthsession
    add_binary /usr/bin/tpm2_policypcr
    add_binary /usr/bin/tpm2_policyauthvalue
    add_binary /usr/bin/tpm2_unseal
    add_binary /usr/bin/tpm2_flushcontext
    add_binary /usr/bin/tpm2_pcrextend
    add_binary /usr/lib/libargon2.so
    add_binary /usr/lib/libargon2.so.1
    add_binary /usr/bin/systemd-ask-password
    add_binary /usr/bin/cryptsetup
    add_binary /usr/local/bin/security-manager/idp/idp-tpm

    cat >"$BUILDROOT/usr/lib/systemd/system/idp-tpm.service" <<EOF
[Unit]
Description=IDP TPM
DefaultDependencies=no
After=plymouth-start.service
Before=cryptsetup-pre.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/hooks/idp-tpm run_hook
EOF

    add_systemd_unit cryptsetup-pre.target
    cd "$BUILDROOT/usr/lib/systemd/system/sysinit.target.wants"
    ln -sf ../cryptsetup-pre.target cryptsetup-pre.target
    ln -sf ../idp-tpm.service idp-tpm.service

}

help() {
    cat <<HELPEOF
This hook allows for reading the encryption key from TPM.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
